networks:
  caddy:
    external: true

services:
  webhook-proxy:
    image: ghcr.io/amphora/slack-to-glue-webhook:latest
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    networks:
      - caddy
